### ISSUE TITLE
Some motion selections do not work

### ISSUE THREAD

**Issue by skitoo** [t9md/atom-vim-mode-plus#661]
- Atom version 
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

- vim-mode-plus version.
0.80.0

- You disabled vim-mode?  
Yes

Some motion selections do not work :

* ```v i {``` 
* ```v i [```
* ```v i ` ```

Same with

* ```v a {``` 
* ```v a [```
* ```v a ` ```

**Comment by ithil** [comment]
They work for me.    
Can you try to go into visual mode and then call the commands manually via the command palette to see whether it's just the key bindings not working? I.e. call `Vim Mode Plus: Inner Curly Bracket`and so on.

**Comment by skitoo** [comment]
When I call the commands manually, it works !
I think the problem comes from `Alt-Gr` touch. I use an AZERTY keyboard and to make `{`, `[` and ``` ` ``` the combinaison with this touch is required.

**Comment by ithil** [comment]
Weird. There have been issues with the AltGr key in the past but they were supposedly all fixed in Atom 1.12. (See: https://atom.io/packages/keyboard-localization and http://blog.atom.io/2016/10/17/the-wonderful-world-of-keyboards.html )

As a workaround you could use:    
* `v i q` which works for *all* quotes, i.e. single quotes `'`, double quotes `"` and back ticks `` ` `` 
* `v i b` for parentheses ` ( ) `
* `v i B` for curly brackets ` { } `
etc.

For square brackets you would have to specify custom key bindings, though.

**Comment by t9md** [comment]
Thanks @ithil for helping.
As like `v i q`  is mapped to `inner-any-quote`, `v i s` is mapped to `inner-qny-pair`.

Although these keymaps resides for a long time, these are still experimental.
For true compatibility to pure-Vim `i s` should be used for `inner-sentence`, but I vmp still not support sentence text-object so I can use it for any-pair.

**Comment by lydell** [comment]
For me, `i[` and `i{` always trigger the `[` and `{` motions. I’ve tested with en-US QWERTY.

**Comment by edgydot** [comment]
@skitoo: FWIW, on my German keyboard (on Linux), I got `i {` working by using `i altgraph {` in the mapping:
```
'atom-text-editor.vim-mode-plus.operator-pending-mode, atom-text-editor.vim-mode-plus.visual-mode':
  'i altgraph {': 'vim-mode-plus:inner-curly-bracket'
```

**Comment by fmthoma** [comment]
This is probably still due to atom/atom-keymap#126. At least I tracked the problem down to this in early 2016, not sure if this still applies.

Basically, Atom treats AltGr (aka ISO_Leve3_Shift) and other modifiers (like ISO_Level5_Shift) as normal keys instead of modifiers, so they interrupt the key sequence instead of waiting for a non-modifier key to be pressed. @edgydot's solution works by explicitly matching the AltGr key event.

**Comment by t9md** [comment]
@edgydot , @fmthoma  thanks for workaround and explain existing issue.
I finally understand what and why this kind of report sometimes pops up.

Although my keyboard layout(US106) have no such issue.
I have some idea to temporally workaround issue, give me comment, how do you think following idea?

## TextObject key which might not work

This is excerpt from [default keymaps](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson).
Which I thinks affected by this issue.

```
'atom-text-editor.vim-mode-plus.operator-pending-mode, atom-text-editor.vim-mode-plus.visual-mode':
  'i "': 'vim-mode-plus:inner-double-quote'
  'a "': 'vim-mode-plus:a-double-quote'
  "i '": 'vim-mode-plus:inner-single-quote'
  "a '": 'vim-mode-plus:a-single-quote'
  'i `': 'vim-mode-plus:inner-back-tick'
  'a `': 'vim-mode-plus:a-back-tick'
  'i {': 'vim-mode-plus:inner-curly-bracket'
  'i }': 'vim-mode-plus:inner-curly-bracket'
  'a {': 'vim-mode-plus:a-curly-bracket'
  'a }': 'vim-mode-plus:a-curly-bracket'
  'i <': 'vim-mode-plus:inner-angle-bracket'
  'i >': 'vim-mode-plus:inner-angle-bracket'
  'a <': 'vim-mode-plus:a-angle-bracket'
  'a >': 'vim-mode-plus:a-angle-bracket'
  'i [': 'vim-mode-plus:inner-square-bracket'
  'i ]': 'vim-mode-plus:inner-square-bracket'
  'a [': 'vim-mode-plus:a-square-bracket'
  'a ]': 'vim-mode-plus:a-square-bracket'
  'i (': 'vim-mode-plus:inner-parenthesis'
  'i )': 'vim-mode-plus:inner-parenthesis'
  'a (': 'vim-mode-plus:a-parenthesis'
  'a )': 'vim-mode-plus:a-parenthesis'
```

## How do you think adding following **default** keymap?

**correct me if it include no problematic one**.

```
'atom-text-editor.vim-mode-plus.operator-pending-mode, atom-text-editor.vim-mode-plus.visual-mode':
  'i altgraph "': 'vim-mode-plus:inner-double-quote'
  'a altgraph "': 'vim-mode-plus:a-double-quote'
  "i altgraph '": 'vim-mode-plus:inner-single-quote'
  "a altgraph '": 'vim-mode-plus:a-single-quote'
  'i altgraph `': 'vim-mode-plus:inner-back-tick'
  'a altgraph `': 'vim-mode-plus:a-back-tick'
  'i altgraph {': 'vim-mode-plus:inner-curly-bracket'
  'i altgraph }': 'vim-mode-plus:inner-curly-bracket'
  'a altgraph {': 'vim-mode-plus:a-curly-bracket'
  'a altgraph }': 'vim-mode-plus:a-curly-bracket'
  'i altgraph <': 'vim-mode-plus:inner-angle-bracket'
  'i altgraph >': 'vim-mode-plus:inner-angle-bracket'
  'a altgraph <': 'vim-mode-plus:a-angle-bracket'
  'a altgraph >': 'vim-mode-plus:a-angle-bracket'
  'i altgraph [': 'vim-mode-plus:inner-square-bracket'
  'i altgraph ]': 'vim-mode-plus:inner-square-bracket'
  'a altgraph [': 'vim-mode-plus:a-square-bracket'
  'a altgraph ]': 'vim-mode-plus:a-square-bracket'
  'i altgraph (': 'vim-mode-plus:inner-parenthesis'
  'i altgraph )': 'vim-mode-plus:inner-parenthesis'
  'a altgraph (': 'vim-mode-plus:a-parenthesis'
  'a altgraph )': 'vim-mode-plus:a-parenthesis'
```
